var userGuess = document.getElementById('user-guess')
var submitBtn = document.getElementById('submit-btn')
var clearBtn = document.getElementById('clear-btn')
var resetBtn = document.getElementById('reset-btn')
var numberGuesser = document.querySelector('h1')
